class Susops < Formula
  include Language::Python::Virtualenv

  desc "SSH SOCKS5 proxy manager — Python TUI + PAC server"
  homepage "https://github.com/mashb1t/susops"
  url "https://github.com/mashb1t/susops/archive/v3.0.0.tar.gz"
  sha256 "PLACEHOLDER"
  license "MIT"

  depends_on "socat"
  depends_on "python@3.12"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Generated by: python scripts/compute_resource_shas.py
  # Updated by:   python scripts/update_homebrew_sha.py <version>

  resource "aiohappyeyeballs" do
    url "https://files.pythonhosted.org/packages/source/a/aiohappyeyeballs/aiohappyeyeballs-2.6.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "aiohttp" do
    url "https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.13.5.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "aiosignal" do
    url "https://files.pythonhosted.org/packages/source/a/aiosignal/aiosignal-1.4.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "annotated-types" do
    url "https://files.pythonhosted.org/packages/source/a/annotated_types/annotated_types-0.7.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "attrs" do
    url "https://files.pythonhosted.org/packages/source/a/attrs/attrs-26.1.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "cffi" do
    url "https://files.pythonhosted.org/packages/source/c/cffi/cffi-1.17.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-46.0.7.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "frozenlist" do
    url "https://files.pythonhosted.org/packages/source/f/frozenlist/frozenlist-1.8.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/source/i/idna/idna-3.11.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "linkify-it-py" do
    url "https://files.pythonhosted.org/packages/source/l/linkify_it_py/linkify_it_py-2.1.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/source/m/markdown_it_py/markdown_it_py-4.0.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "mdit-py-plugins" do
    url "https://files.pythonhosted.org/packages/source/m/mdit_py_plugins/mdit_py_plugins-0.5.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/source/m/mdurl/mdurl-0.1.2.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "multidict" do
    url "https://files.pythonhosted.org/packages/source/m/multidict/multidict-6.7.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "platformdirs" do
    url "https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-4.9.4.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "plotext" do
    url "https://files.pythonhosted.org/packages/source/p/plotext/plotext-5.3.2.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "propcache" do
    url "https://files.pythonhosted.org/packages/source/p/propcache/propcache-0.4.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "psutil" do
    url "https://files.pythonhosted.org/packages/source/p/psutil/psutil-7.2.2.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/source/p/pycparser/pycparser-2.22.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "pydantic" do
    url "https://files.pythonhosted.org/packages/source/p/pydantic/pydantic-2.12.5.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "pydantic-core" do
    url "https://files.pythonhosted.org/packages/source/p/pydantic_core/pydantic_core-2.41.5.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/source/p/pygments/pygments-2.20.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/source/r/rich/rich-14.3.3.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "ruamel-yaml" do
    url "https://files.pythonhosted.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.19.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "textual" do
    url "https://files.pythonhosted.org/packages/source/t/textual/textual-8.2.3.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "textual-plotext" do
    url "https://files.pythonhosted.org/packages/source/t/textual_plotext/textual_plotext-1.0.1.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "typing-extensions" do
    url "https://files.pythonhosted.org/packages/source/t/typing_extensions/typing_extensions-4.15.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "typing-inspection" do
    url "https://files.pythonhosted.org/packages/source/t/typing_inspection/typing_inspection-0.4.2.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "uc-micro-py" do
    url "https://files.pythonhosted.org/packages/source/u/uc_micro_py/uc_micro_py-1.0.3.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "yarl" do
    url "https://files.pythonhosted.org/packages/source/y/yarl/yarl-1.23.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    output = shell_output("#{bin}/susops ps 2>&1", 3)
    assert_match "stopped", output
  end
end
