name: Build & Release SusOps

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          tag="${{ github.event.release.tag_name }}"
          version="${tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Configure Git actions user
        run: |
          git config --global user.name  "actions-user"
          git config --global user.email "actions@github.com"

      - name: Bump Homebrew Cask
        run: |
          brew tap mashb1t/susops
          brew bump-formula-pr \
            mashb1t/susops/susops \
            --version ${{ steps.version.outputs.version }} \
            --no-browse --no-fork
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_PR_TOKEN }}
